//
// Generated file, do not edit! Created by opp_msgtool 6.0 from MeshPacket.msg.
//

#ifndef __LORA_MESH_MESHPACKET_M_H
#define __LORA_MESH_MESHPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace lora_mesh {

class MeshPacket;
class SensorDataPacket;
class SosBeaconPacket;

}  // namespace lora_mesh

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address

// cplusplus {{
#include "inet/networklayer/common/L3Address.h"
using namespace inet;
// }}


namespace lora_mesh {

/**
 * Class generated from <tt>MeshPacket.msg:42</tt> by opp_msgtool.
 * <pre>
 * // =============================================================================
 * // 1. MeshPacket — Temel taşıyıcı zarf
 * // =============================================================================
 * // Her mesh paketinde bulunması gereken minimum başlık bilgileri.
 * // HybridGateway, ağa çıkarken `destinationGateway` alanını doldurur.
 * // MeshNode bu alanı okuyarak hangi GW'ye doğru yönleneceğine karar verir.
 * //
 * // Toplam başlık boyutu: ~10 bayt (2 × L3Address/IPv4 + 2 × int alanları)
 * // =============================================================================
 * class MeshPacket extends inet::FieldsChunk
 * {
 *     // Paketi gönderen kaynak düğümün ağ adresi
 *     inet::L3Address sourceAddress;
 * 
 *     // Paketin ulaşmak istediği hedef gateway'in adresi.
 *     // HybridGateway bu alanı broadcast yaparken atar; MeshNode, C_i hesabında
 *     // bu hedefe doğru en iyi next-hop'u bulmak için kullanır.
 *     inet::L3Address destinationGateway;
 * 
 *     // Paketin geçtiği atlama (hop) sayacı — döngü önleme için
 *     int hopCount = 0;
 * 
 *     // Uçtan uca sıra numarası — yinelenen paket tespiti için
 *     int sequenceNumber = 0;
 * }
 * </pre>
 */
class MeshPacket : public ::inet::FieldsChunk
{
  protected:
    ::inet::L3Address sourceAddress;
    ::inet::L3Address destinationGateway;
    int hopCount = 0;
    int sequenceNumber = 0;

  private:
    void copy(const MeshPacket& other);

  protected:
    bool operator==(const MeshPacket&) = delete;

  public:
    MeshPacket();
    MeshPacket(const MeshPacket& other);
    virtual ~MeshPacket();
    MeshPacket& operator=(const MeshPacket& other);
    virtual MeshPacket *dup() const override {return new MeshPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const ::inet::L3Address& getSourceAddress() const;
    virtual ::inet::L3Address& getSourceAddressForUpdate() { handleChange();return const_cast<::inet::L3Address&>(const_cast<MeshPacket*>(this)->getSourceAddress());}
    virtual void setSourceAddress(const ::inet::L3Address& sourceAddress);

    virtual const ::inet::L3Address& getDestinationGateway() const;
    virtual ::inet::L3Address& getDestinationGatewayForUpdate() { handleChange();return const_cast<::inet::L3Address&>(const_cast<MeshPacket*>(this)->getDestinationGateway());}
    virtual void setDestinationGateway(const ::inet::L3Address& destinationGateway);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MeshPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MeshPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>MeshPacket.msg:75</tt> by opp_msgtool.
 * <pre>
 * // =============================================================================
 * // 2. SensorDataPacket — Standart tarla sensörü verisi
 * // =============================================================================
 * // SensorLoRaApp.cc tarafından üretilen 11 baytlık little-endian payload'u
 * // OMNeT++ simülasyon katmanında alan alan temsil eder.
 * //
 * // Byte düzeni (SensorLoRaApp.cc ile birebir):
 * //   [0..1]  seqNum         int16_t   2 bayt
 * //   [2..3]  temperature_dC int16_t   2 bayt  (°C × 10 → 235 = 23.5 °C)
 * //   [4]     humidity       uint8_t   1 bayt  (% 0..100)
 * //   [5]     soilMoisture   uint8_t   1 bayt  (% 0..100)
 * //   [6]     rain           uint8_t   1 bayt  (0=yok, 1=hafif, 2=orta, 3=şiddetli)
 * //   [7..8]  pressure_hPa   int16_t   2 bayt  (hPa, offset +900 → 1013 hPa = 113)
 * //   [9]     lightLevel     uint8_t   1 bayt  (0=karanlık .. 255=tam güneş)
 * //             TOPLAM                11 bayt  (+ MeshPacket başlığı)
 * // =============================================================================
 * class SensorDataPacket extends MeshPacket
 * {
 *     // Sıra numarası (SensorLoRaApp.cc'deki seqNum ile aynı)
 *     short seqNum = 0;
 * 
 *     // ── Mesh Röle Teslimat Metadata (PacketForwarder.meshRelayIn için) ──────
 *     // LoRa Spreading Factor (7..12). forwardToMesh() orijinal LoRaMacFrame'den
 *     // kopyalar; PacketForwarder NS2'ye teslim ederken LoRaMacFrame içine yazar.
 *     int loRaSF = 9;
 * 
 *     // Orijinal sensör MAC adresi (string olarak; MacAddress.str() çıktısı).
 *     // Ör: "0a:aa:00:00:00:01". PacketForwarder bunu MacAddress(str)'a dönüştürür.
 *     string transmitterMacStr = "0a:aa:00:00:00:01";
 * 
 *     // Sinyal kalitesi (orijinal GW-Sensor ölçümü, NS2 istatistikleri için)
 *     double rssi = -100.0;
 *     double snir = 10.0;
 * 
 *     // Sıcaklık — ondalık hassasiyeti korumak için ×10 tamsayı olarak
 *     // Örnek: 23.5 °C → 235, -5.0 °C → -50
 *     short temperature_dC = 0;
 * 
 *     // Bağıl nem [0..100] %
 *     int humidity = 0;
 * 
 *     // Toprak nemi [0..100] %
 *     int soilMoisture = 0;
 * 
 *     // Yağış kodu: 0=yok, 1=hafif, 2=orta, 3=şiddetli
 *     int rain = 0;
 * 
 *     // Atmosfer basıncı [hPa], offset +900 uygulanmış
 *     // Örnek: 1013 hPa → 113 olarak saklanır
 *     short pressure_hPa = 0;
 * 
 *     // Işık seviyesi [0..255] (0=tam karanlık, 255=tam güneş)
 *     int lightLevel = 0;
 * }
 * </pre>
 */
class SensorDataPacket : public ::lora_mesh::MeshPacket
{
  protected:
    short seqNum = 0;
    int loRaSF = 9;
    ::omnetpp::opp_string transmitterMacStr = "0a:aa:00:00:00:01";
    double rssi = -100.0;
    double snir = 10.0;
    short temperature_dC = 0;
    int humidity = 0;
    int soilMoisture = 0;
    int rain = 0;
    short pressure_hPa = 0;
    int lightLevel = 0;

  private:
    void copy(const SensorDataPacket& other);

  protected:
    bool operator==(const SensorDataPacket&) = delete;

  public:
    SensorDataPacket();
    SensorDataPacket(const SensorDataPacket& other);
    virtual ~SensorDataPacket();
    SensorDataPacket& operator=(const SensorDataPacket& other);
    virtual SensorDataPacket *dup() const override {return new SensorDataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual short getSeqNum() const;
    virtual void setSeqNum(short seqNum);

    virtual int getLoRaSF() const;
    virtual void setLoRaSF(int loRaSF);

    virtual const char * getTransmitterMacStr() const;
    virtual void setTransmitterMacStr(const char * transmitterMacStr);

    virtual double getRssi() const;
    virtual void setRssi(double rssi);

    virtual double getSnir() const;
    virtual void setSnir(double snir);

    virtual short getTemperature_dC() const;
    virtual void setTemperature_dC(short temperature_dC);

    virtual int getHumidity() const;
    virtual void setHumidity(int humidity);

    virtual int getSoilMoisture() const;
    virtual void setSoilMoisture(int soilMoisture);

    virtual int getRain() const;
    virtual void setRain(int rain);

    virtual short getPressure_hPa() const;
    virtual void setPressure_hPa(short pressure_hPa);

    virtual int getLightLevel() const;
    virtual void setLightLevel(int lightLevel);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SensorDataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SensorDataPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>MeshPacket.msg:129</tt> by opp_msgtool.
 * <pre>
 * // =============================================================================
 * // 3. SosBeaconPacket — Acil durum imdat sinyali (AjanGateway uyanışı)
 * // =============================================================================
 * // MeshRouting.cc, aşağıdaki tetikleyicilerden birini algıladığında bu paketi
 * // mesh'e yayınlar:
 * //   a) Darboğaz: Q_i >= congestionThreshold (varsayılan %80) VE fallback komşu yok
 * //   b) Bölgesel çöküş: tüm komşular stale / neighbor tablosu boş
 * //   c) Ana gateway erişilemez: isOnlineGateway=true olan komşu kalmadı
 * //
 * // AjanGateway, bu paketi dinler ve kendi uplink bağlantısını (4G/satellit)
 * // aktive ederek bölgesel yedek çıkış noktası olarak devreye alır.
 * //
 * // `isUrgent = true` alan bu paket, MeshNode'larda normal veri paketlerine
 * // göre öncelikli işlenir (kuyrukta ön tarafa alınır).
 * // =============================================================================
 * class SosBeaconPacket extends MeshPacket
 * {
 *     // Her zaman true — normal veri paketlerinden ayırt etmek için
 *     // MeshNode yönlendirici, bu bayrakla SOS trafiğini önceliklendirir
 *     bool isUrgent = true;
 * 
 *     // Alarm nedeni kodu
 *     //   0 = CONGESTION       — yerel kuyruk darboğazı (Q >= eşik)
 *     //   1 = REGIONAL_FAILURE — birden fazla komşu erişilemez
 *     //   2 = GATEWAY_DOWN     — tüm online-GW komşuları kayboldu
 *     //   3 = LINK_DEGRADED    — ortalama RSSI dramatik düşüş tespit etti
 *     int reasonCode = 0;
 * 
 *     // SOS'u üreten düğümün kimlik dizgesi (Qtenv'de okunabilirlik için)
 *     // Örnek: "meshNode[2]"
 *     string senderNodeId = "";
 * 
 *     // Alarm anındaki kuyruk doluluk oranı [0.0 .. 1.0]
 *     // computeCost() içindeki Q_i/Q_max değeri buraya kopyalanır
 *     double congestionLevel = 0.0;
 * 
 *     // Alarm anındaki neighbor tablosunda online GW sayısı
 *     // 0 ise tam yalıtım (total isolation) senaryosu
 *     int onlineGatewayCount = 0;
 * 
 *     // SOS üretildiği andaki ortalama komşu RSSI [dBm]
 *     // Sinyal kalitesi izleme ve post-mortem analiz için
 *     double averageRssi_dBm = 0.0;
 * }
 * </pre>
 */
class SosBeaconPacket : public ::lora_mesh::MeshPacket
{
  protected:
    bool isUrgent_ = true;
    int reasonCode = 0;
    ::omnetpp::opp_string senderNodeId = "";
    double congestionLevel = 0.0;
    int onlineGatewayCount = 0;
    double averageRssi_dBm = 0.0;

  private:
    void copy(const SosBeaconPacket& other);

  protected:
    bool operator==(const SosBeaconPacket&) = delete;

  public:
    SosBeaconPacket();
    SosBeaconPacket(const SosBeaconPacket& other);
    virtual ~SosBeaconPacket();
    SosBeaconPacket& operator=(const SosBeaconPacket& other);
    virtual SosBeaconPacket *dup() const override {return new SosBeaconPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool isUrgent() const;
    virtual void setIsUrgent(bool isUrgent);

    virtual int getReasonCode() const;
    virtual void setReasonCode(int reasonCode);

    virtual const char * getSenderNodeId() const;
    virtual void setSenderNodeId(const char * senderNodeId);

    virtual double getCongestionLevel() const;
    virtual void setCongestionLevel(double congestionLevel);

    virtual int getOnlineGatewayCount() const;
    virtual void setOnlineGatewayCount(int onlineGatewayCount);

    virtual double getAverageRssi_dBm() const;
    virtual void setAverageRssi_dBm(double averageRssi_dBm);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SosBeaconPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SosBeaconPacket& obj) {obj.parsimUnpack(b);}


}  // namespace lora_mesh


namespace omnetpp {

template<> inline lora_mesh::MeshPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<lora_mesh::MeshPacket*>(ptr.get<cObject>()); }
template<> inline lora_mesh::SensorDataPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<lora_mesh::SensorDataPacket*>(ptr.get<cObject>()); }
template<> inline lora_mesh::SosBeaconPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<lora_mesh::SosBeaconPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __LORA_MESH_MESHPACKET_M_H

