#!/bin/bash
# =============================================================================
# run_faz21.sh — Auto-generated by generate_massive_topology.py  [phase=21]
# =============================================================================
# Toplam config : 84
# Run/config    : 36  (sensorSF 7..12 × meshSF 7..12)
# Toplam run    : 3024
# Phase         : 21  (sigma=4.5, gamma=2.8, obstacle_loss=3.5dB (foliage/wood, Arazi1 dogal))
#
# Kullanım:
#   bash run_faz21.sh [--jobs N] [--from-config IDX] [--to-config IDX]
#   bash run_faz21.sh --config Faz21_GW2_Mesh1_MIN  # tek config
#   bash run_faz21.sh --jobs 4 --from-config 0 --to-config 9  # ilk 10 config
#
# Resume: .done flag'leri sayesinde kaldığı yerden devam eder.
#   Silmek için: rm -rf logs_massive_faz2_v2/<ConfigName>
# =============================================================================

set -euo pipefail

PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="${PROJ_DIR}/lora_mesh_projesi_dbg"
OMNETPP_DIR="/home/eren/Desktop/bitirme_lora_kod/omnetpp-6.0-linux-x86_64/omnetpp-6.0"
FLORA="/home/eren/Desktop/bitirme_lora_kod/workspace/flora"
INET="/home/eren/Desktop/bitirme_lora_kod/workspace/inet4.4"
RUNS_PER_CONFIG=36
LOG_BASE="${PROJ_DIR}/logs_massive_faz2_v2"

export LD_LIBRARY_PATH="${OMNETPP_DIR}/lib:${FLORA}/src:${INET}/src${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# ── Config listesi (auto-generated) ──────────────────────────────────────────
CONFIGS=(
    "Faz21_GW2_Mesh1_MIN"
    "Faz21_GW2_Mesh1_MAX"
    "Faz21_GW2_Mesh2_MIN"
    "Faz21_GW2_Mesh2_MAX"
    "Faz21_GW2_Mesh3_MIN"
    "Faz21_GW2_Mesh3_MAX"
    "Faz21_GW2_Mesh4_MIN"
    "Faz21_GW2_Mesh4_MAX"
    "Faz21_GW2_Mesh5_MIN"
    "Faz21_GW2_Mesh5_MAX"
    "Faz21_GW2_Mesh6_MIN"
    "Faz21_GW2_Mesh6_MAX"
    "Faz21_GW2_Mesh7_MIN"
    "Faz21_GW2_Mesh7_MAX"
    "Faz21_GW3_Mesh1_MIN"
    "Faz21_GW3_Mesh1_MAX"
    "Faz21_GW3_Mesh2_MIN"
    "Faz21_GW3_Mesh2_MAX"
    "Faz21_GW3_Mesh3_MIN"
    "Faz21_GW3_Mesh3_MAX"
    "Faz21_GW3_Mesh4_MIN"
    "Faz21_GW3_Mesh4_MAX"
    "Faz21_GW3_Mesh5_MIN"
    "Faz21_GW3_Mesh5_MAX"
    "Faz21_GW3_Mesh6_MIN"
    "Faz21_GW3_Mesh6_MAX"
    "Faz21_GW3_Mesh7_MIN"
    "Faz21_GW3_Mesh7_MAX"
    "Faz21_GW4_Mesh1_MIN"
    "Faz21_GW4_Mesh1_MAX"
    "Faz21_GW4_Mesh2_MIN"
    "Faz21_GW4_Mesh2_MAX"
    "Faz21_GW4_Mesh3_MIN"
    "Faz21_GW4_Mesh3_MAX"
    "Faz21_GW4_Mesh4_MIN"
    "Faz21_GW4_Mesh4_MAX"
    "Faz21_GW4_Mesh5_MIN"
    "Faz21_GW4_Mesh5_MAX"
    "Faz21_GW4_Mesh6_MIN"
    "Faz21_GW4_Mesh6_MAX"
    "Faz21_GW4_Mesh7_MIN"
    "Faz21_GW4_Mesh7_MAX"
    "Faz21_GW5_Mesh1_MIN"
    "Faz21_GW5_Mesh1_MAX"
    "Faz21_GW5_Mesh2_MIN"
    "Faz21_GW5_Mesh2_MAX"
    "Faz21_GW5_Mesh3_MIN"
    "Faz21_GW5_Mesh3_MAX"
    "Faz21_GW5_Mesh4_MIN"
    "Faz21_GW5_Mesh4_MAX"
    "Faz21_GW5_Mesh5_MIN"
    "Faz21_GW5_Mesh5_MAX"
    "Faz21_GW5_Mesh6_MIN"
    "Faz21_GW5_Mesh6_MAX"
    "Faz21_GW5_Mesh7_MIN"
    "Faz21_GW5_Mesh7_MAX"
    "Faz21_GW6_Mesh1_MIN"
    "Faz21_GW6_Mesh1_MAX"
    "Faz21_GW6_Mesh2_MIN"
    "Faz21_GW6_Mesh2_MAX"
    "Faz21_GW6_Mesh3_MIN"
    "Faz21_GW6_Mesh3_MAX"
    "Faz21_GW6_Mesh4_MIN"
    "Faz21_GW6_Mesh4_MAX"
    "Faz21_GW6_Mesh5_MIN"
    "Faz21_GW6_Mesh5_MAX"
    "Faz21_GW6_Mesh6_MIN"
    "Faz21_GW6_Mesh6_MAX"
    "Faz21_GW6_Mesh7_MIN"
    "Faz21_GW6_Mesh7_MAX"
    "Faz21_GW7_Mesh1_MIN"
    "Faz21_GW7_Mesh1_MAX"
    "Faz21_GW7_Mesh2_MIN"
    "Faz21_GW7_Mesh2_MAX"
    "Faz21_GW7_Mesh3_MIN"
    "Faz21_GW7_Mesh3_MAX"
    "Faz21_GW7_Mesh4_MIN"
    "Faz21_GW7_Mesh4_MAX"
    "Faz21_GW7_Mesh5_MIN"
    "Faz21_GW7_Mesh5_MAX"
    "Faz21_GW7_Mesh6_MIN"
    "Faz21_GW7_Mesh6_MAX"
    "Faz21_GW7_Mesh7_MIN"
    "Faz21_GW7_Mesh7_MAX"
)
TOTAL_CONFIGS=${#CONFIGS[@]}

# ── Argüman parse ─────────────────────────────────────────────────────────────
JOBS=1
FROM_CFG=0
TO_CFG=$(( TOTAL_CONFIGS - 1 ))

while [[ $# -gt 0 ]]; do
    case $1 in
        --jobs)         JOBS="$2";     shift 2 ;;
        --from-config)  FROM_CFG="$2"; shift 2 ;;
        --to-config)    TO_CFG="$2";   shift 2 ;;
        --config)
            CFG_NAME="$2"
            for idx in "${!CONFIGS[@]}"; do
                if [[ "${CONFIGS[$idx]}" == "$CFG_NAME" ]]; then
                    FROM_CFG=$idx; TO_CFG=$idx; break
                fi
            done
            shift 2 ;;
        *) echo "Bilinmeyen argüman: $1"; exit 1 ;;
    esac
done

mkdir -p "${LOG_BASE}"
cd "${PROJ_DIR}"

# ── Tek bir run'ı çalıştıran fonksiyon ───────────────────────────────────────
run_one() {
    local config="$1"
    local run="$2"
    local log_dir="${LOG_BASE}/${config}"
    local log="${log_dir}/run_${run}.log"
    local done_flag="${log_dir}/run_${run}.done"

    mkdir -p "${log_dir}"

    # Resume: tamamlanmış run'ı atla
    if [[ -f "${done_flag}" ]]; then
        return 0
    fi

    "${BIN}" -m -c "${config}" -r "${run}" -u Cmdenv \
        -n ".:/home/eren/Desktop/bitirme_lora_kod/workspace/flora/src:/home/eren/Desktop/bitirme_lora_kod/workspace/inet4.4/src" \
        > "${log}" 2>&1

    local exit_code=$?
    if [[ ${exit_code} -eq 0 ]]; then
        touch "${done_flag}"
        (
            flock -x 200
            DONE_COUNT=$(find "${LOG_BASE}" -name "*.done" 2>/dev/null | wc -l)
            echo "[DONE] ${config} run=${run}  (${DONE_COUNT}/3024 toplam)"
        ) 200>"${LOG_BASE}/.lock"
    else
        echo "[FAIL] ${config} run=${run}  exit=${exit_code}  log=${log}"
        return ${exit_code}
    fi
}

export -f run_one
export BIN FLORA INET LOG_BASE PROJ_DIR

# ── Özet ──────────────────────────────────────────────────────────────────────
echo "=== run_massive.sh ==="
echo "Toplam config : ${TOTAL_CONFIGS}"
echo "Seçilen range : ${FROM_CFG} .. ${TO_CFG} ($(( TO_CFG - FROM_CFG + 1 )) config)"
echo "Run/config    : ${RUNS_PER_CONFIG}"
echo "Paralel       : ${JOBS} iş"
echo "Logs          : ${LOG_BASE}/"
echo ""

WALL_START=$(date +%s)
TOTAL_FAILED=0

# ── Ana döngü ─────────────────────────────────────────────────────────────────
for cfg_idx in $(seq "${FROM_CFG}" "${TO_CFG}"); do
    config="${CONFIGS[$cfg_idx]}"
    log_dir="${LOG_BASE}/${config}"

    echo "─── Config [${cfg_idx}/${TOTAL_CONFIGS}]: ${config}"

    if [[ ${JOBS} -gt 1 ]] && command -v parallel &>/dev/null; then
        seq 0 $(( RUNS_PER_CONFIG - 1 )) | \
            parallel -j "${JOBS}" --line-buffer run_one "${config}" {}
    elif [[ ${JOBS} -gt 1 ]]; then
        # GNU Parallel yoksa: bash background jobs ile paralel (& + wait -n)
        _RUNNING=0
        for run in $(seq 0 $(( RUNS_PER_CONFIG - 1 ))); do
            run_one "${config}" "${run}" &
            _RUNNING=$(( _RUNNING + 1 ))
            if (( _RUNNING >= JOBS )); then
                wait -n 2>/dev/null || wait
                _RUNNING=$(( _RUNNING - 1 ))
            fi
        done
        wait
    else
        for run in $(seq 0 $(( RUNS_PER_CONFIG - 1 ))); do
            run_one "${config}" "${run}" || (( TOTAL_FAILED++ )) || true
        done
    fi

    # Config özet satırı
    DONE_FOR_CFG=$(find "${log_dir}" -name "*.done" 2>/dev/null | wc -l)
    echo "    → ${DONE_FOR_CFG}/${RUNS_PER_CONFIG} tamamlandı"
done

WALL_END=$(date +%s)
ELAPSED=$(( WALL_END - WALL_START ))

echo ""
echo "=== Batch tamamlandı ==="
echo "Geçen süre   : $(( ELAPSED / 3600 ))s $(( (ELAPSED % 3600) / 60 ))dk $(( ELAPSED % 60 ))sn"
echo "Başarısız    : ${TOTAL_FAILED}"
echo "SCA dosyaları: ${PROJ_DIR}/results_faz2_v2/Faz21_*.sca"
